# Build configuration for AWS SAM
version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "auth-app"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "auth-app"
region = "us-east-1"
image_repositories = []

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"